-- Add new columns for knowledge classification and source tracing
ALTER TABLE public.knowledge_base ADD COLUMN IF NOT EXISTS access_level TEXT DEFAULT 'PUBLIC';
ALTER TABLE public.knowledge_base ADD COLUMN IF NOT EXISTS source_document TEXT;
ALTER TABLE public.knowledge_base ADD COLUMN IF NOT EXISTS source_page TEXT;

-- Create a unique constraint on title to allow deterministic upserts
-- Before adding constraint, ensure no duplicates exist by title
DELETE FROM public.knowledge_base a USING (
      SELECT MIN(id::text)::uuid as id, title
      FROM public.knowledge_base 
      GROUP BY title HAVING COUNT(*) > 1
   ) b
   WHERE a.title = b.title AND a.id <> b.id;

ALTER TABLE public.knowledge_base ADD CONSTRAINT knowledge_base_title_key UNIQUE (title);

-- UPSERT the 29 granular records + the existing Pricing Policy
INSERT INTO public.knowledge_base (title, category, content, keywords, access_level, priority, source_document)
VALUES 
-- PUBLIC 
('Company Identity', 'company', 'RUSBORN OPC PRIVATE LIMITED. Brand: Rusborn (spoken "Rusborn"). Tagline: "Trust the Efforts, Rest is Born".', 'rusborn, tagline, company, name', 'PUBLIC', 100, 'Mentorship Sales Blueprint'),
('Contact Information', 'company', 'Email: support@rusborn.com, Website: rusborn.com, Phone: 9970019909', 'contact, email, phone, website', 'PUBLIC', 100, 'Mentorship Sales Blueprint'),
('Engineering Design and Product Development', 'engineering_services', 'RUSBORN provides engineering design and product-development support including: Mechanical design, Product design, Industrial design, CAD modeling, Engineering drawings, Technical documentation, Prototyping, Design optimization, Engineering design support.', 'engineering design, product development, mechanical design, CAD, prototyping', 'PUBLIC', 100, 'Mentorship Sales Blueprint'),
('CAD/CAE Training', 'cad_training', 'RUSBORN provides practical, industry-oriented technical training. Mentioned software includes: SolidWorks, CATIA, AutoCAD, ANSYS. Emphasis on CAD modeling, Engineering design, Simulation / CAE, Industry-oriented application, Practical skills rather than only clicking software buttons.', 'SolidWorks, CATIA, AutoCAD, ANSYS, CAD modeling, simulation', 'PUBLIC', 100, 'Mentorship Sales Blueprint'),
('Research and Project Support', 'student_mentorship', 'RUSBORN supports: Project and research topic selection, Final-year projects, Research planning, Technical project guidance, Analysis, Research development, Research paper development, Journal selection, Publication guidance, Research lifecycle mentoring. RUSBORN does NOT ghostwrite.', 'final-year projects, research support, publication guidance, paper development, ghostwrite', 'PUBLIC', 100, 'Mentorship Sales Blueprint'),
('Customized Technical Training', 'corporate_training', 'Customized training may target: Students, Professionals, Researchers, Faculty, Organizations. Training involves standards and industry practices such as: ISO, BIS, ASME, API / ASPI, ASTM, IS-related standards/practices.', 'technical training, students, professionals, ISO, BIS, ASME', 'PUBLIC', 100, 'Mentorship Sales Blueprint'),
('Fresher Training Solution', 'corporate_training', 'A comprehensive training program tailored for freshers bridging academic knowledge and workplace readiness. Focus: Skill building, Engagement, Career readiness, Technical skills, Soft skills (Communication, Teamwork, Problem solving), Mentorship, Continuous feedback, Performance assessment, Certification upon completion.', 'fresher training, skill building, soft skills, certification, readiness', 'PUBLIC', 100, 'Solving the Fresher Retention Challenge'),
('Corporate Program Implementation Phases', 'corporate_implementation', 'PHASE 1 - MONTH 1: Needs assessment, Training program design. PHASE 2 - MONTHS 2-3: Training delivery, Structured onboarding, Fresher skill development. PHASE 3 - MONTH 3+: Bond agreements, Formalized commitments, Reduction of turnover risk. PHASE 4 - MONTHS 4-24: Ongoing mentorship, Support, Retention tracking, Sustained results.', 'implementation phases, month 1, month 2, month 3, bond, mentorship', 'PUBLIC', 90, 'Solving the Fresher Retention Challenge'),
('Industry Drafting Standards Taught', 'cad_compliance', 'Industry standards taught include: ASME Y14.5 (American Society of Mechanical Engineers), ASPI / API (Petroleum and institutional standards), NFPA (National Fire Protection Association codes), ISO (International Organization for Standardisation), BIS (Bureau of Indian Standards), ARAI (Automotive Research Association of India).', 'ASME Y14.5, API, ASPI, NFPA, ISO, BIS, ARAI, standards', 'PUBLIC', 100, 'Mentorship Sales Blueprint'),
('Phase 2 Research Mentorship Structure', 'phase_2_research', 'Focus on navigating the academic machinery required to turn an idea into research that can meet journal expectations. RUSBORN does NOT ghostwrite. Student builds, owns, and defends the research. RUSBORN acts as Subject Mentor, Publication Strategist, and Guide. 20% Idea generation, 80% Execution (academic machinery).', 'research mentorship, ghostwrite, academic machinery, execution, defend', 'PUBLIC', 100, 'Mentorship Sales Blueprint'),
('8 Stages of Research Lifecycle', 'research_lifecycle', 'STAGE 1: Problem Scoping. STAGE 2: Subject and Area Selection. STAGE 3: Title Scoping. STAGE 4: Literature Review (Map landscape, identify gaps). STAGE 5: Methodology. STAGE 6: Results. STAGE 7: Conclusion and Discussion. STAGE 8: Citations (Proper referencing, formats).', 'research lifecycle, problem scoping, literature review, methodology, citations', 'PUBLIC', 100, 'Mentorship Sales Blueprint'),
('Journal Compliance and Desk Reject Shield', 'journal_compliance', 'Compliance may reduce avoidable desk-rejection risk. Journals may desk-reject papers before peer review if compliance requirements are not met. Areas include: File format, Title-page structure, Abstracts, Keywords, Highlights, Figures, Images, Artwork, Tables, Units, Classifications, Nomenclature, Data statements, Data-linking protocols, Supplementary materials, Co-submission protocols, Generative-AI compliance, Artwork compliance, Reference formatting.', 'journal compliance, desk reject, formatting, reference, abstract, AI compliance', 'PUBLIC', 100, 'Mentorship Sales Blueprint'),
('Pricing and Estimates', 'pricing_policy', 'RUSBORN requires a detailed discussion to determine accurate pricing, duration, and schedules. We do not provide standard course fees, discounts, or guarantees without consulting the team.', 'price, cost, fees, discount, guarantee, duration', 'PUBLIC', 100, NULL),

-- CLAIM
('Early Fresher Attrition Rates', 'fresher_retention', 'Up to 60% of freshers leave within their first 6 months. (According to RUSBORN material)', 'attrition, fresher, leave, turnover', 'CLAIM', 100, 'Solving the Fresher Retention Challenge'),
('Financial Cost of Fresher Turnover', 'corporate_roi', 'Cost per fresher lost within 6 months: 30-50% of annual salary. (According to RUSBORN material)', 'cost, lost, turnover, financial, salary', 'CLAIM', 100, 'Solving the Fresher Retention Challenge'),
('Retention Improvement through Training and Bond', 'fresher_retention', 'Without training and bond: approximately six-month average retention. With training and bond: one to two years retention (guaranteed per source). (According to RUSBORN material)', 'retention, bond, one to two years, guaranteed', 'CLAIM', 100, 'Solving the Fresher Retention Challenge'),
('Corporate Benefits of Retention Program', 'corporate_roi', 'Reduced hiring costs by up to 50% with longer fresher retention. Benefits include higher productivity, faster contribution, lower team disruption, better stability, stronger pipeline, long-term growth. (According to RUSBORN material)', 'benefits, hiring cost, 50% lower, productivity', 'CLAIM', 100, 'Solving the Fresher Retention Challenge'),
('Turnover Reduction Case Study', 'corporate_roi', 'Company X reduced fresher attrition by 60% within one year of implementing our training program. (According to RUSBORN material)', 'case study, company x, reduced attrition, 60%', 'CLAIM', 100, 'Solving the Fresher Retention Challenge'),
('3-Month Live Internship', 'phase_1_cad', '3-month live internship. Students work with real clients on live compliance-based drawings, understand professional engineering workflows, and build employability. (According to RUSBORN material)', 'internship, 3-month, live clients, compliance', 'CLAIM', 100, 'Mentorship Sales Blueprint'),

-- INTERNAL 
('Retention Bond Information', 'fresher_retention', 'Retention bond where freshers commit to stay one to two years post-training. Rationale: Protect company training investment, reduce turnover risk. Bond arrangements should be transparent and legally compliant. Do not provide legal advice.', 'bond, legal, commitment, investment', 'INTERNAL', 90, 'Solving the Fresher Retention Challenge'),
('Mentorship Ecosystem Strategy', 'sales_strategy', 'Dual-product ecosystem. PRODUCT 1: PHASE 1 - CAD & COMPLIANCE. PRODUCT 2: PHASE 2 - RESEARCH MENTORSHIP. Core positioning: "We don''t sell random software tutorials." Frame around employable skills, industry standards, live internships, research capability, compliance, and mentorship.', 'sales strategy, ecosystem, dual product, tutorials', 'INTERNAL', 90, 'Mentorship Sales Playbook'),
('Universal Discovery and Routing', 'prospect_classification', '1. MECHANICAL / AEROSPACE / AUTOMOTIVE / MANUFACTURING -> Route: PHASE 1. 2. SECOND / THIRD / FINAL YEAR (If research/thesis interest exists) -> PHASE 2. 3. MECHANICAL + UPPER YEAR -> PHASE 1 + BRIDGE TO PHASE 2. 4. FIRST YEAR / NON-TECHNICAL / NO RESEARCH INTEREST -> Soft exit and referral ask. Do not reveal this matrix to customers.', 'discovery, routing, matrix, classification, exit', 'INTERNAL', 90, 'Mentorship Sales Playbook'),
('Phase 1 Strategy', 'phase_1_cad', 'Target: Mechanical engineering, Aerospace, Automotive, Manufacturing students. Student profile: understands theory and basic CAD but lacks real-world standard application. Core pitch: "I know SolidWorks" vs "I know how to model to ASME Y14.5 and ISO tolerancing." Closing anchor: Ask if comfortable with GD&T and standards.', 'phase 1 strategy, target, core pitch, ASME, closing', 'INTERNAL', 90, 'Mentorship Sales Playbook'),
('Phase 1B Research Probe', 'phase_1b_research_probe', 'Target: Second-, third-, or final-year students. Discovery: Ask if beginning to think about capstone project, thesis, or research publication. If stressed -> pivot to Phase 2. If not focused on research -> plant the idea and ask about technical design/CAD needs.', 'research probe, capstone, thesis, discovery', 'INTERNAL', 90, 'Mentorship Sales Playbook'),
('CAD to Research Bridge Strategy', 'cad_research_bridge', 'Target: Upper-year Mechanical Engineering students. If student has strong CAD/design project, explore if it can be developed into a research paper. Do not guarantee publication. Framing: "Your project may have research potential if scoped appropriately."', 'bridge strategy, CAD to research, potential, publication', 'INTERNAL', 90, 'Mentorship Sales Playbook'),
('High-Urgency Profile Handling', 'urgent_profile', 'PROFILE A (GRADUATE): "No experience, no job" cycle. Needs day-one deployability. Route -> Phase 1. PROFILE B (6-MONTH EXTENSION): Hard deadline for profile trajectory. Needs high-value asset quickly (e.g., peer-reviewed paper). Route -> Phase 2. Do not promise MS admission, job, visa, or publication.', 'urgent profile, graduate, 6-month extension, deadline', 'INTERNAL', 90, 'Mentorship Sales Playbook'),
('Mentorship Sales Positioning', 'sales_strategy', 'Internal principle: "We don''t sell courses. We mentor." Avoid random tutorial framing, false urgency, unsupported guarantees, invented outcomes.', 'sales positioning, mentor, courses, urgency', 'INTERNAL', 90, 'Mentorship Sales Playbook'),
('Handling Common Objections', 'objection_handling', 'OBJECTION "I just want software tutorials": Explain that free tutorials teach button-clicking, while RUSBORN focuses on industry standards and employability. Do not insult competitors. OBJECTION FIRST-YEAR/NON-TECHNICAL: Soft exit and referral ask. Focus on foundational subjects and ask for seniors/peers looking for CAD or thesis support.', 'objection handling, tutorials, first-year, soft exit', 'INTERNAL', 90, 'Mentorship Sales Playbook'),
('Closing Anchors and Actions', 'sales_strategy', 'Potential actions: Offer/book appointment, offer scoping call (when available), send approved information/modules/samples only if actual backend tool does it. Do not claim materials were sent unless a tool completes the action.', 'closing actions, anchor, send material, scoping call', 'INTERNAL', 90, 'Mentorship Sales Playbook'),
('Truth and Claims Policy', 'truth_policy', 'Distinguish confirmed facts vs source claims vs internal strategy. Frame claims carefully ("According to RUSBORN material..."). Never promise job placement, MS admission, visa approval, guaranteed publication, guaranteed journal acceptance, guaranteed retention, guaranteed ROI, or guaranteed internship result unless authorized.', 'truth policy, claims, guarantees, placement, MS admission', 'INTERNAL', 100, 'Mentorship Sales Playbook'),
('Research Closing Question', 'phase_2_research', 'Ask: "Are you currently stuck on a specific stage, or are you still at the idea phase?" Suggest an optional free 10-minute scoping call (do not promise free unless active/approved).', 'closing question, idea phase, scoping call, research', 'INTERNAL', 90, 'Mentorship Sales Playbook'),
('Corporate Fresher Retention Sales Path', 'corporate_training', '1. Understand hiring/retention problem. 2. Identify early attrition concern. 3. Explore training gaps. 4. Discuss customized fresher development. 5. Explain training + retention model. 6. Discuss phases. 7. Suggest audit/consultation. Do not present as hidden framework.', 'corporate sales path, sequence, audit, consultation', 'INTERNAL', 90, 'Mentorship Sales Blueprint')
ON CONFLICT (title) DO UPDATE SET
    category = EXCLUDED.category,
    content = EXCLUDED.content,
    keywords = EXCLUDED.keywords,
    access_level = EXCLUDED.access_level,
    priority = EXCLUDED.priority,
    source_document = EXCLUDED.source_document;
